### ISSUE TITLE
Mynah-ui parse paragraph as code block.

### ISSUE THREAD

**Issue by chengoramazon** [aws/mynah-ui#70]
## Problem

mynah-ui parse paragraph as code block.

**Actual input**
```
Hi, I'm the Amazon Q Developer Agent for software development.

    I can generate code to implement new functionality across your workspace. We'll start by discussing an implementation plan, and then we can review and regenerate code based on your feedback.

    To get started, describe the task you are trying to accomplish.
```

![bug-in-example](https://github.com/aws/mynah-ui/assets/143654391/f7777364-b422-490d-965a-1a5d7a95b374)

## Steps to reproduce the issue

1. Go to https://aws.github.io/mynah-ui/ 
2. Enter
```
Hi, I'm the Amazon Q Developer Agent for software development.

    I can generate code to implement new functionality across your workspace. We'll start by discussing an implementation plan, and then we can review and regenerate code based on your feedback.

    To get started, describe the task you are trying to accomplish.
```
3. Same thing happens in Amazon Q /dev

![Bug](https://github.com/aws/mynah-ui/assets/143654391/3403d378-8d93-4eba-b4e0-69c56dcad010)

## Expected behavior

Parse as paragraph.

## System details (run the `AWS: About Toolkit` command)

-   OS:
-   Visual Studio Code version:
-   AWS Toolkit version:

**Comment by dogusata** [comment]
This is is reverted back to keep markdown default behavior as is without overriding the parsing mechanism. The reason behind that is that markdown reads the empty spaces as code blocks. 
Can be shown in some markdown generators like Lorem Markdown.

Here's a basic markdown output it generates for a code block:
<img width="686" alt="image" src="https://github.com/user-attachments/assets/1352b3a9-67fd-415a-9ead-5d85eed006c5">


Since the support of the markdown in the prompt input field is crucial to give the ability to user writing markdown elements like code blocks and inline codes, as discussed with UX team the decision is to keep the prompt input to support default markdown formats without overriding the rendering.

**Comment by dogusata** [comment]
Another useful information:

<img width="820" alt="image" src="https://github.com/user-attachments/assets/b6ec374b-8adf-4bf5-aba6-c3ead88519dc">
