### ISSUE TITLE
Nested list parsing doesn't work in Mynah UI

### ISSUE THREAD

**Issue by tverney** [aws/mynah-ui#97]
## Problem

We've seen responses from LLM being answered in a wrong level when nested (see screenshots).

![image (1)](https://github.com/user-attachments/assets/bee5f3b2-da58-4fb9-9cdd-59735a01b193)
![Screenshot 2024-08-14 at 1 21 36 PM](https://github.com/user-attachments/assets/858327b0-9445-41bd-b7e5-8f9854e87737)

## Steps to reproduce the issue

If I copy the file for nested examples in Mynah UI, add as an input response, it doesn't format/work as expected.
<img width="724" alt="Screenshot 2024-08-14 at 1 42 18 PM" src="https://github.com/user-attachments/assets/86264b63-0ff4-472d-8e0d-8f03f87a22f0">
<img width="586" alt="Screenshot 2024-08-14 at 1 42 48 PM" src="https://github.com/user-attachments/assets/0b9ba3d1-9781-4728-a3c3-15e2c884202b">

## Expected behaviour

It should parse it as expected in Markdown spec: https://ref.coddy.tech/markdown/markdown-nested-lists

## System details

- OS:
- Tested enviroment:
    - [X] Web (Demo app)
    - [X] VSCode Amazon Q Chat
    - [ ] JetBrains IntelliJ Amazon Q Chat
- Enviroment extension version (if applicable): 
- [ ] Enviroment is remote

**Comment by volodkevych** [comment]
Formatting is also broken for other functionality. For example, if I "Send to prompt" selected code block, code indentation is lost:
<img width="971" alt="Screenshot 2024-08-21 at 10 19 16" src="https://github.com/user-attachments/assets/04a5ee23-e549-4056-b547-93b6b6088868">

The issue was caused by this change: https://github.com/aws/mynah-ui/pull/72/files.
